CONTRIBUTING.md, README.md
Please verify above files and let me know if any changes are required, if seems fine then go ahead and merge this.
=> Added CONTRBUTING.md and README.md

style.css
=> "UI improvements"

CONTRIBUTING.md
i improved overall contributing.md and made it looks charming
=> improved overall contributing.md

index.html, index.js
Hey! I improved usability by using a form tag, so users can also press [enter] to save a todo.
The input message is now also deleted once it has been saved.
Let me know if you want more help :)
=> Improved usability

index.js, style.css
=> this is my first commit in hacktober fest

index.html, index.js, style.css
@Zack-Dx I have added edit and dark mode buttons please merge it and make it hactoberfest accepted.
=> edit and dark mode theme button added

index.html, index.js, style.css
=> Revert "dark mode"

.vscode/settings.json, index.html, style.css
I have added welcome message on top of input , plz review
=> welcome message added

index.html, index.js, style.css
Please check the status now, updated with required changes.
=> Updated UI with required changes

index.html, style.css
PR #26 
I have made some UI changes in the Nav Bar made some Text Easy to read, and Added Animation in Edit Text
=> feat: Added transitions and UI changes

index.html, style.css
This PR resolves issue #17 
In this project, edit functionality was already added, but it was lacking the important info of how we can edit the note, because note-editng process of this project was somewhat different from normal note-editing processes, which can be understand only by seeing the code and this is not practical.
So, in order to resolve the problem I added the note editing guideline in the main dashboard of the website.
The screenshot for the same is attached herewith:
=> Edit functionality improved

style.css
=> Added a Lavender tint to the background in dark mode

CODE_OF_CONDUCT.md
PR for issue #34 
Issue link -[https://github.com/Zack-Dx/Mini-TODO/issues/34](url)
=> added code of conduct markdown file

index.js, style.css
=> Upgraded edit functionality

index.html, style.css
This PR is for resolving the issue #41
=> change editing guideline

index.html, index.js, style.css
hello,
sorry for the last one, I did blunder in that now I think it's perfect.
Have a Review pls.
=> Popup Msg alert box  added.

README.md
=> fixed errors in Readme.md

index.html, index.js, style.css
Closes #54 
There was an error in naming a variable, resulting in the error. It has been renamed successfully, and thus the error has been resolved.
I have also removed the console.log statements from the .js file, as it might result in security issue in the long run and in production.
I have also made some UI improvements such as scrollbar width, height.
I have also made grammatical corrections to alerts, that appear when user creates, edits or deletes notes.
=> Bug Fixed + UI improvements

index.js
I did some research and found that using console.log is a vulnerability, so I thought it would be a good idea to make these changes!
=> Removed console.log

index.html
=> Added logo to the title bar

index.html, style.css
=> Revert "added animated bg"

index.js
=> fix input width while editing note

index.html, index.js, style.css
Please merge the pull request and add hacktoberfest
=> Enhanced the UI, added "search note" pallet.

index.js
Added copy to clipboard functionality.
Screenshot:
=> feat: added copy to clipboard functionality

index.html, index.js, style.css
=> Removed unused code (after Sync fork)

index.html, index.js, style.css
@Zack-Dx  plese check my update
Before 
After
=> Fix footer padding (done)

index.js
The issue with search, where it does not show any results has been resolved and the changing of notes dimensions has been resolved. 
Closes #110
=> Search bug resolved

style.css
changed size of input text and add note button and make blueberry keep responsixe
=> changed size of input text and add note button and make blueberry keep.

style.css
@Zack-Dx I have added some height and width card are align in one line and new card will in next line. You can check.
Also added some space between each card.
=> fix: added some height width to box

css/style.css, js/index.js
I have added an overflow to avoid overshoot of notes. Also a few extra changes are shown since I had run the eslint and prettier commands as specified in readme.
=> added property to avoid saved note overflow

package.json
=> Update package.json add keywords and description (Done)

css/style.css, index.html
1. created a generic class for buttons
2. general behavior for them
3. added a smooth transformation in the opposite direction
4. started prettier
=> refactoring button class

js/index.js
Fixing the problem of copying text with backward compatibility support
=> (fix) Copy text button

index.html, manifest.json
Add manifest.json to fix the following issue
=> Add manifest.json
